### ISSUE TITLE
Error when running `npm test` or `npm run lint-test`

### ISSUE THREAD

**Issue by mainangethe** [exercism/javascript#635]
I recently completed the Is Leap for Javascript.

* I tried to run my tests with the command ```javascript  npm test ```.
* I went to the link provided by the CLI.
* **Expected:** to see the results of my unit tests,
* **Actual:** I got a Type Error.

> cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object 

Here's my "exercism debug":
```
**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: ubuntu, x64
Build OS/Architecture /
Home Dir: /Users/ngethe
Config file: /Users/ngethe/.exercism.json
API Key: *******
Exercises Directory: /Users/ngethe/exercism/javascript
> exercism-javascript@0.0.0 test /home/ngethe/exercism/javascript/leap
> jest --no-cache ./*

**ERROR MESSAGE**
 FAIL  ./leap.spec.js
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'

      at exports.default (node_modules/jest-util/build/create_process_object.js:15:34)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.444s
Ran all test suites matching /.\/README.md|.\/isLeap.js|.\/leap.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json/i.

**Comment by mainangethe** [comment]
![tiny-error-screenshot](https://user-images.githubusercontent.com/41260290/54081640-dd255c00-4318-11e9-8d76-cb7767040513.png)

**Comment by tejasbubane** [comment]
This is an issue with Node v11.11 - https://github.com/facebook/create-react-app/issues/6591 For now there is no fix apart from downgrading node version.

**Comment by micalgenus** [comment]
The project does not seem to use create-react-app. The following was resolved in jest: Facebook/jest#8050

If you use the version of jest and Babel-jest at v24.2.0-alpha.0 or later, you can resolve it. The latest version of best is v24.3.1. 😄

**Comment by tejasbubane** [comment]
@micalgenus Yes. This project does not use `create-react-app` and the issue was in Jest. I just happened to find that issue in create-react-app repo and used that issue link.

Alright so we need to update Jest. I tried doing the same after Jest 24 released recently and ran into all sorts of weird issues due to babel 7 ([ref](https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly)) I will give it a try again today.

**Comment by mainangethe** [comment]
@micalgenus - I tried installing jest and babel-jest @ v24.2.0-alpha.0

And still getting an error. Now it's saying `Cannot find module './leap' from 'leap.spec.js'
`
![tiny-npm-jest- -babel-v24 2-failing-16032019](https://user-images.githubusercontent.com/41260290/54471209-8b704c00-47c6-11e9-810d-dbcd5c3e8b86.png)

**Comment by SleeplessByte** [comment]
And are you _certain_ there is a `leap.js` file in that directory?

**Comment by SleeplessByte** [comment]
Resolved in Node 11.12

**Comment by tejasbubane** [comment]
@mainangethe Please fetch new version of the exercise and try again. Reopen the issue if you are still seeing the issue. Thanks!

**Comment by caledrummond90** [comment]
npm run build
chromium tests/testsuite.html
npm run lint

**Comment by SleeplessByte** [comment]
@caledrummond90 I don't know why you posted this in this issue, but there is no `build` script in `exercism/javascript`, and no testsuite.html.
